### ISSUE TITLE
Support for Norpix Seq files

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#153]
Required for Direct Electron cameras (Benjamin Bammes)

**Comment by sk1p** [comment]
See also: 

 * C impl for reading 8bit norpix seq files https://github.com/nclack/seq (weird license though)
 * https://www.norpix.com/support/Norpix2MATLAB.m matlab implementation by norpix, nonfree license as far as I can see?

Using those as a reference, we should be able to implement a reader once we have sample data.

**Comment by sk1p** [comment]
See also: https://github.com/soft-matter/pims

**Comment by uellue** [comment]
It should support dark reference and gain maps, refs #154

**Comment by sk1p** [comment]
As a note: @jhgee mentioned that some data was taken without having proper synchronization, this means having frames before and/or after the actual acquisition in the file. So this is another use case where more complicated "re-shaping" of data is needed /cc @AnandBaburajan 

On another note, the seq files don't contain any information about the scan, so there was a question if we could read this from a "sidecar" file, like we do with other formats with their proprietary implementations. One idea would be to have a simple file, maybe in `.ini` format, or `.yml`, which contains that information. This idea could even be extended to other formats that need additional information, like raw. Something like this:

my_dataset.yml:

```yaml
format: SEQ
path: something.seq
scan_size: [256, 256]
dark_frame: dark.tif
```

my_other_dataset.yml:

```yaml
format: RAW
path: other.bin
dtype: u2
scan_size: [256, 256]
detector_size: [128, 128]
dark_frame: dark.tif
```

These yml files could then provide one-click opening in LiberTEM, even if the underlying raw dataset doesn't provide enough information.
