### ISSUE TITLE
Parameter sidecar files

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#768]
From #153:

SEQ files don't contain any information about the scan, so there was a question if we could read this from a "sidecar" file, like we do with other formats with their proprietary implementations. One idea would be to have a simple file, maybe in `.ini` format, or `.yml`, which contains that information. This idea could even be extended to other formats that need additional information, like raw. Something like this:

my_dataset.yml:

```yaml
format: SEQ
path: something.seq
scan_size: [256, 256]
dark_frame: dark.tif
```

my_other_dataset.yml:

```yaml
format: RAW
path: other.bin
dtype: u2
scan_size: [256, 256]
detector_size: [128, 128]
dark_frame: dark.tif
```

These yml files could then provide one-click opening in LiberTEM, even if the underlying raw dataset doesn't provide enough information.
